FROM larbys/pytorch:pytorch1.0.1post2_ubuntu16.04_mkl

MAINTAINER taritree.wongjirad@tufts.edu

# SparseConvNet
RUN apt update -y && apt install -y libsparsehash-dev && \
    apt autoremove -y && \
    cd /tmp && git clone https://github.com/nutufts/SparseConvNet && \
    cd SparseConvNet && chmod +x build.sh && \
    CUDA_HOME=/usr/local/cuda-10.0;PATH=/usr/local/cuda-10.0/bin:${PATH} ./build.sh
