FROM larbys/pytorch:1.3.0_py2_cpu

MAINTAINER taritree.wongjirad@tufts.edu

# SparseConvNet
RUN apt update -y && apt install -y libsparsehash-dev && \
    apt autoremove -y && \
    cd /tmp && git clone https://github.com/nutufts/SparseConvNet && \
    cd SparseConvNet && git checkout larbys_cpu && \
    ./build_cpu.sh && \
    cd / && rm -rf /tmp/SparseConvNet
RUN pip install xgboost && pip install scikit-learn
