FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

MAINTAINER taritree.wongjirad@tufts.edu

# DEPENDENCIES
RUN apt-get update -y \
    && apt install -y libeigen3-dev libboost-all-dev libopenblas-openmp-dev git ninja-build cmake build-essential python3-pip emacs vim wget unzip tar \
    && apt-get autoremove -y && apt-get clean -y

# PYTORCH
RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 \
    && python3 -m pip cache purge

# ADD Minkowski engine

##############################################
# You should modify this to match your GPU compute capability
ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0 8.0+PTX"
##############################################

ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"

ENV MAX_JOBS=4

RUN pip3 install -U git+https://github.com/NVIDIA/MinkowskiEngine -v --no-deps \
                           --install-option="--force_cuda" \
			   --install-option="--cuda_home=/usr/local/cuda" \			   
                           --install-option="--blas=openblas" \
			   && python3 -m pip cache purge			   

