FROM larbys/ubdl:depsonly_py3_u20.04_cu11.1_pytorch1.9_root6.24.02

MAINTAINER taritree.wongjirad@tufts.edu

# UBDL DEPENDENCEIS
RUN apt-get update -y \
    && apt install -y rsync libeigen3-dev libboost-all-dev emacs vim gdb \
    && apt-get autoremove -y && apt-get clean -y

# ADD PIP MODULES
RUN pip3 install pyyaml typing figcan zmq pexpect paramiko_tunnel selectors tensorboard tensorboardX msgpack msgpack-numpy

# XGBOOST 1.4.2
RUN cd /tmp && git clone --recursive https://github.com/dmlc/xgboost.git xgboost_v1.4.2 && cd xgboost_v1.4.2 && git checkout -b v1.4.2 v1.4.2 \
    && git submodule init && git submodule update \
    && mkdir -p /tmp/xgboost_build \
    && cd /tmp/xgboost_build && cmake ../xgboost_v1.4.2 && make install && cd /tmp && rm -rf /tmp/xgboost_build \
    && rm -rf /tmp/xgboost_v1.4.2

# clean up nvidia lists
RUN  rm -rf /var/lib/apt/lists/* \
         /etc/apt/sources.list.d/cuda.list \
          /etc/apt/sources.list.d/nvidia-ml.list 
RUN apt-get update 

#ADD "https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin" "/tmp/cuda-ubuntu2004.pin"
#ADD "https://developer.download.nvidia.com/compute/cuda/11.3.1/local_installers/cuda-repo-ubuntu2004-11-3-local_11.3.1-465.19.01-1_amd64.deb" "/tmp/cuda-repo-ubuntu2004-11-3-local_11.3.1-465.19.01-1_amd64.deb"
#ADD "https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub" "/etc/apt/7fa2af80.pub"
#RUN cat /etc/apt/7fa2af80.pub | apt-key add - && \
#    dpkg -i /tmp/cuda-repo-ubuntu2004-11-3-local_11.3.1-465.19.01-1_amd64.deb && \
#    apt update

# ADD Minkowski engine

##############################################
# You should modify this to match your GPU compute capability
ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0 8.0+PTX"
##############################################

ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"

# Install dependencies
RUN apt-get install -y git ninja-build cmake build-essential libopenblas-dev \
    xterm xauth openssh-server tmux wget mate-desktop-environment-core && apt clean -y


# For faster build, use more jobs.
ENV MAX_JOBS=4
RUN CXX=g++-9;CUDA_HOME=/usr/local/cuda;PATH=/usr/local/cuda/bin:${PATH} pip3 install -U git+https://github.com/NVIDIA/MinkowskiEngine -v --no-deps \
                           --install-option="--force_cuda" \
			   --install-option="--cuda_home=/usr/local/cuda" \			   
                           --install-option="--blas=openblas" 
			   
#RUN apt-get update -y && apt install -y python3-dev libopenblas-dev && apt autoremove -y && apt clean -y
#RUN pip3 install torch ninja
#RUN CXX=g++-9;CUDA_HOME=/usr/local/cuda;PATH=/usr/local/cuda/bin:${PATH} pip3 install -U MinkowskiEngine \
#    --install-option="--blas=openblas" \
#    --install-option="--force_cuda"  \
#    --install-option="--cuda-home=/usr/local/cuda" \
#    -v --no-deps
