FROM larbys/ubdl:depsonly_py3_u20.04_cu11.1_pytorch1.9_root6.24.02

MAINTAINER taritree.wongjirad@tufts.edu

# UBDL
RUN apt-get update -y \
    && apt install -y rsync libeigen3-dev libboost-all-dev emacs vim gdb \
    && apt-get autoremove -y && apt-get clean -y

# ADD PIP MODULES
RUN pip3 install pyyaml typing figcan zmq pexpect paramiko_tunnel selectors tensorboard tensorboardX msgpack msgpack-numpy

# ADD Minkowski engine

##############################################
# You should modify this to match your GPU compute capability
ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0 8.0+PTX"
##############################################

ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"

# Install dependencies
RUN apt-get update
RUN apt-get install -y git ninja-build cmake build-essential libopenblas-dev \
    xterm xauth openssh-server tmux wget mate-desktop-environment-core

RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

# For faster build, use more jobs.
ENV MAX_JOBS=4
RUN CXX=g++-9;CUDA_HOME=/usr/local/cuda;PATH=/usr/local/cuda/bin:${PATH} pip3 install -U git+https://github.com/NVIDIA/MinkowskiEngine -v --no-deps \
                           --install-option="--force_cuda" \
			   --install-option="--cuda_home=/usr/local/cuda" \			   
                           --install-option="--blas=openblas" 
			   
#RUN apt-get update -y && apt install -y python3-dev libopenblas-dev && apt autoremove -y && apt clean -y
#RUN pip3 install torch ninja
#RUN CXX=g++-9;CUDA_HOME=/usr/local/cuda;PATH=/usr/local/cuda/bin:${PATH} pip3 install -U MinkowskiEngine \
#    --install-option="--blas=openblas" \
#    --install-option="--force_cuda"  \
#    --install-option="--cuda-home=/usr/local/cuda" \
#    -v --no-deps
