FROM larbys/root:6.16.00_ubuntu18.04

MAINTAINER taritree.wongjirad@tufts.edu

# OPENCV 3.4: DEPS
RUN apt-get update && \
    apt-get install -y build-essential \
	    	    	cmake \
			git \
			libavcodec-dev \
			libavformat-dev \
			libdc1394-22-dev \
			libgtk2.0-dev \
			libjpeg-dev \
			libpng-dev \
			libswscale-dev \
			libtiff-dev \
			libtbb2 \
			libtbb-dev \
			pkg-config \
			python-dev \
			python-numpy \
			python-pip \
			python-pandas && \
    pip install root_numpy && \
    apt-get autoremove -y & apt-get clean -y

# OPENCV 3.4: BUILD
RUN mkdir -p /tmp/build && cd /tmp/ && \
    git clone https://github.com/opencv/opencv source && cd source && \
    git checkout 3.4.0 && cd /tmp/build && \
    cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/usr/local /tmp/source && \
    make -j4 && make install -j4 && \
    rm -r /tmp/build && rm -r /tmp/source
